################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (10.3-2021.10)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F1xx_HAL_Driver/Src \
Drivers/display \
Drivers/lvgl/demos/benchmark/assets \
Drivers/lvgl/demos/benchmark \
Drivers/lvgl/demos/gltf \
Drivers/lvgl/demos/keypad_encoder \
Drivers/lvgl/demos \
Drivers/lvgl/demos/music/assets \
Drivers/lvgl/demos/music \
Drivers/lvgl/demos/render/assets \
Drivers/lvgl/demos/render \
Drivers/lvgl/demos/stress \
Drivers/lvgl/demos/vector_graphic/assets \
Drivers/lvgl/demos/vector_graphic \
Drivers/lvgl/demos/widgets/assets \
Drivers/lvgl/demos/widgets \
Drivers/lvgl/env_support/pikascript \
Drivers/lvgl/env_support/rt-thread \
Drivers/lvgl/env_support/rt-thread/squareline \
Drivers/lvgl/examples/anim \
Drivers/lvgl/examples/assets \
Drivers/lvgl/examples/assets/emoji \
Drivers/lvgl/examples/event \
Drivers/lvgl/examples/get_started \
Drivers/lvgl/examples/grad \
Drivers/lvgl/examples/layouts/flex \
Drivers/lvgl/examples/layouts/grid \
Drivers/lvgl/examples/libs/barcode \
Drivers/lvgl/examples/libs/bmp \
Drivers/lvgl/examples/libs/ffmpeg \
Drivers/lvgl/examples/libs/freetype \
Drivers/lvgl/examples/libs/gif \
Drivers/lvgl/examples/libs/gltf \
Drivers/lvgl/examples/libs/gstreamer \
Drivers/lvgl/examples/libs/libjpeg_turbo \
Drivers/lvgl/examples/libs/libpng \
Drivers/lvgl/examples/libs/libwebp \
Drivers/lvgl/examples/libs/lodepng \
Drivers/lvgl/examples/libs/qrcode \
Drivers/lvgl/examples/libs/rlottie \
Drivers/lvgl/examples/libs/svg \
Drivers/lvgl/examples/libs/tiny_ttf \
Drivers/lvgl/examples/libs/tjpgd \
Drivers/lvgl/examples/others/file_explorer \
Drivers/lvgl/examples/others/font_manager \
Drivers/lvgl/examples/others/fragment \
Drivers/lvgl/examples/others/gestures \
Drivers/lvgl/examples/others/gridnav \
Drivers/lvgl/examples/others/ime \
Drivers/lvgl/examples/others/imgfont \
Drivers/lvgl/examples/others/monkey \
Drivers/lvgl/examples/others/observer \
Drivers/lvgl/examples/others/snapshot \
Drivers/lvgl/examples/others/translation \
Drivers/lvgl/examples/porting \
Drivers/lvgl/examples/porting/osal \
Drivers/lvgl/examples/scroll \
Drivers/lvgl/examples/styles \
Drivers/lvgl/examples/widgets/animimg \
Drivers/lvgl/examples/widgets/arc \
Drivers/lvgl/examples/widgets/arclabel \
Drivers/lvgl/examples/widgets/bar \
Drivers/lvgl/examples/widgets/button \
Drivers/lvgl/examples/widgets/buttonmatrix \
Drivers/lvgl/examples/widgets/calendar \
Drivers/lvgl/examples/widgets/canvas \
Drivers/lvgl/examples/widgets/chart \
Drivers/lvgl/examples/widgets/checkbox \
Drivers/lvgl/examples/widgets/dropdown \
Drivers/lvgl/examples/widgets/image \
Drivers/lvgl/examples/widgets/imagebutton \
Drivers/lvgl/examples/widgets/keyboard \
Drivers/lvgl/examples/widgets/label \
Drivers/lvgl/examples/widgets/led \
Drivers/lvgl/examples/widgets/line \
Drivers/lvgl/examples/widgets/list \
Drivers/lvgl/examples/widgets/lottie \
Drivers/lvgl/examples/widgets/menu \
Drivers/lvgl/examples/widgets/msgbox \
Drivers/lvgl/examples/widgets/obj \
Drivers/lvgl/examples/widgets/roller \
Drivers/lvgl/examples/widgets/scale \
Drivers/lvgl/examples/widgets/slider \
Drivers/lvgl/examples/widgets/span \
Drivers/lvgl/examples/widgets/spinbox \
Drivers/lvgl/examples/widgets/spinner \
Drivers/lvgl/examples/widgets/switch \
Drivers/lvgl/examples/widgets/table \
Drivers/lvgl/examples/widgets/tabview \
Drivers/lvgl/examples/widgets/textarea \
Drivers/lvgl/examples/widgets/tileview \
Drivers/lvgl/examples/widgets/win \
Drivers/lvgl/src/core \
Drivers/lvgl/src/debugging/monkey \
Drivers/lvgl/src/debugging/sysmon \
Drivers/lvgl/src/debugging/test \
Drivers/lvgl/src/debugging/vg_lite_tvg \
Drivers/lvgl/src/display \
Drivers/lvgl/src/draw/convert/helium \
Drivers/lvgl/src/draw/convert \
Drivers/lvgl/src/draw/convert/neon \
Drivers/lvgl/src/draw/dma2d \
Drivers/lvgl/src/draw/espressif/ppa \
Drivers/lvgl/src/draw/eve \
Drivers/lvgl/src/draw \
Drivers/lvgl/src/draw/nanovg \
Drivers/lvgl/src/draw/nema_gfx \
Drivers/lvgl/src/draw/nxp/g2d \
Drivers/lvgl/src/draw/nxp/pxp \
Drivers/lvgl/src/draw/opengles \
Drivers/lvgl/src/draw/renesas/dave2d \
Drivers/lvgl/src/draw/sdl \
Drivers/lvgl/src/draw/snapshot \
Drivers/lvgl/src/draw/sw/blend/helium \
Drivers/lvgl/src/draw/sw/blend \
Drivers/lvgl/src/draw/sw/blend/neon \
Drivers/lvgl/src/draw/sw/blend/riscv_v \
Drivers/lvgl/src/draw/sw \
Drivers/lvgl/src/draw/vg_lite \
Drivers/lvgl/src/drivers/display/drm \
Drivers/lvgl/src/drivers/display/fb \
Drivers/lvgl/src/drivers/display/ft81x \
Drivers/lvgl/src/drivers/display/ili9341 \
Drivers/lvgl/src/drivers/display/lcd \
Drivers/lvgl/src/drivers/display/nv3007 \
Drivers/lvgl/src/drivers/display/nxp_elcdif \
Drivers/lvgl/src/drivers/display/renesas_glcdc \
Drivers/lvgl/src/drivers/display/st7735 \
Drivers/lvgl/src/drivers/display/st7789 \
Drivers/lvgl/src/drivers/display/st7796 \
Drivers/lvgl/src/drivers/display/st_ltdc \
Drivers/lvgl/src/drivers/draw/eve \
Drivers/lvgl/src/drivers/evdev \
Drivers/lvgl/src/drivers/libinput \
Drivers/lvgl/src/drivers/nuttx \
Drivers/lvgl/src/drivers/opengles/assets \
Drivers/lvgl/src/drivers/opengles/glad/src \
Drivers/lvgl/src/drivers/opengles \
Drivers/lvgl/src/drivers/opengles/opengl_shader \
Drivers/lvgl/src/drivers/qnx \
Drivers/lvgl/src/drivers/sdl \
Drivers/lvgl/src/drivers/uefi \
Drivers/lvgl/src/drivers/wayland \
Drivers/lvgl/src/drivers/windows \
Drivers/lvgl/src/drivers/x11 \
Drivers/lvgl/src/font/binfont_loader \
Drivers/lvgl/src/font/fmt_txt \
Drivers/lvgl/src/font/font_manager \
Drivers/lvgl/src/font/imgfont \
Drivers/lvgl/src/font \
Drivers/lvgl/src/indev \
Drivers/lvgl/src/layouts/flex \
Drivers/lvgl/src/layouts/grid \
Drivers/lvgl/src/layouts \
Drivers/lvgl/src/libs/FT800-FT813 \
Drivers/lvgl/src/libs/barcode \
Drivers/lvgl/src/libs/bin_decoder \
Drivers/lvgl/src/libs/bmp \
Drivers/lvgl/src/libs/ffmpeg \
Drivers/lvgl/src/libs/freetype \
Drivers/lvgl/src/libs/frogfs/src \
Drivers/lvgl/src/libs/fsdrv \
Drivers/lvgl/src/libs/gif \
Drivers/lvgl/src/libs/gltf/gltf_data \
Drivers/lvgl/src/libs/gltf/gltf_environment \
Drivers/lvgl/src/libs/gltf/gltf_view/assets \
Drivers/lvgl/src/libs/gltf/math \
Drivers/lvgl/src/libs/gstreamer \
Drivers/lvgl/src/libs/libjpeg_turbo \
Drivers/lvgl/src/libs/libpng \
Drivers/lvgl/src/libs/libwebp \
Drivers/lvgl/src/libs/lodepng \
Drivers/lvgl/src/libs/lz4 \
Drivers/lvgl/src/libs/nanovg \
Drivers/lvgl/src/libs/qrcode \
Drivers/lvgl/src/libs/rle \
Drivers/lvgl/src/libs/rlottie \
Drivers/lvgl/src/libs/svg \
Drivers/lvgl/src/libs/tiny_ttf \
Drivers/lvgl/src/libs/tjpgd \
Drivers/lvgl/src/libs/vg_lite_driver/VGLite \
Drivers/lvgl/src/libs/vg_lite_driver/VGLiteKernel \
Drivers/lvgl/src/libs/vg_lite_driver/lv_vg_lite_hal \
Drivers/lvgl/src \
Drivers/lvgl/src/misc/cache/class \
Drivers/lvgl/src/misc/cache/instance \
Drivers/lvgl/src/misc/cache \
Drivers/lvgl/src/misc \
Drivers/lvgl/src/osal \
Drivers/lvgl/src/others/file_explorer \
Drivers/lvgl/src/others/fragment \
Drivers/lvgl/src/others/translation \
Drivers/lvgl/src/stdlib/builtin \
Drivers/lvgl/src/stdlib/clib \
Drivers/lvgl/src/stdlib \
Drivers/lvgl/src/stdlib/micropython \
Drivers/lvgl/src/stdlib/rtthread \
Drivers/lvgl/src/stdlib/uefi \
Drivers/lvgl/src/themes/default \
Drivers/lvgl/src/themes \
Drivers/lvgl/src/themes/mono \
Drivers/lvgl/src/themes/simple \
Drivers/lvgl/src/tick \
Drivers/lvgl/src/widgets/3dtexture \
Drivers/lvgl/src/widgets/animimage \
Drivers/lvgl/src/widgets/arc \
Drivers/lvgl/src/widgets/arclabel \
Drivers/lvgl/src/widgets/bar \
Drivers/lvgl/src/widgets/button \
Drivers/lvgl/src/widgets/buttonmatrix \
Drivers/lvgl/src/widgets/calendar \
Drivers/lvgl/src/widgets/canvas \
Drivers/lvgl/src/widgets/chart \
Drivers/lvgl/src/widgets/checkbox \
Drivers/lvgl/src/widgets/dropdown \
Drivers/lvgl/src/widgets/gif \
Drivers/lvgl/src/widgets/image \
Drivers/lvgl/src/widgets/imagebutton \
Drivers/lvgl/src/widgets/ime \
Drivers/lvgl/src/widgets/keyboard \
Drivers/lvgl/src/widgets/label \
Drivers/lvgl/src/widgets/led \
Drivers/lvgl/src/widgets/line \
Drivers/lvgl/src/widgets/list \
Drivers/lvgl/src/widgets/lottie \
Drivers/lvgl/src/widgets/menu \
Drivers/lvgl/src/widgets/msgbox \
Drivers/lvgl/src/widgets/objx_templ \
Drivers/lvgl/src/widgets/property \
Drivers/lvgl/src/widgets/roller \
Drivers/lvgl/src/widgets/scale \
Drivers/lvgl/src/widgets/slider \
Drivers/lvgl/src/widgets/span \
Drivers/lvgl/src/widgets/spinbox \
Drivers/lvgl/src/widgets/spinner \
Drivers/lvgl/src/widgets/switch \
Drivers/lvgl/src/widgets/table \
Drivers/lvgl/src/widgets/tabview \
Drivers/lvgl/src/widgets/textarea \
Drivers/lvgl/src/widgets/tileview \
Drivers/lvgl/src/widgets/win \
Drivers/testui \
Drivers/testui/guider_fonts \

