flowchart TD
    A["AT+CIPCLOSE"] 
    --> 
    B["AT+CIPSTART=“TCP”,”wttr.in”,80"] 
    --> 
    C["HTTP GET request"] 
    --> 
    D["AT+CIPSEND=<br>request_length"] 
    --> 
    E["END"]

    style A fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style B fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style C fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style D fill:#f9f,stroke:#333,stroke-width:2px,color:#000
    style E fill:#f00,stroke:#333,stroke-width:2px,color:#000